name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure & Build
        run: |
          mkdir -p build && cd build
          cmake ..
          make -j
